# This workflow will build the two projects

name: core-build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-fe:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Make build FE
        run: make build-fe
      - name: Make validate FE (checks the application's integrity at a basic level)
        run: make validate-fe

  build-be:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Make build BE
        run: make build-be
      - name: Make validate BE (checks the application's integrity at a basic level)
        run: make validate-be

  # This will be developed out to include the deployment of the images
  deploy-apps:
    needs: [build-fe, build-be]
    runs-on: ubuntu-latest

    steps:
      - name: Use Images Here
        run: echo "Using images from previous build step here"
